### PR TITLE
Page/dashboard scaffold

### PR DESCRIPTION
**Pull request by nickzou**
- Install Daisy UI package
- Add some actions for the user on the Dashboard
- Create a user flow for uploading a list from a CSV (or whatever)

The point of this PR is not to set any concrete design decisions but rather to get the ball rolling and provide a practice round of reviews.

### CODE REVIEW

**Review by dazu1990 — COMMENTED** [review]
have you used Daisy UI on the phone before? do you know if it supports gesture interactions well? I was going to look into which component libraries work the best with the phone considering that's the most likely use case for the webapp

**Comment by nickzou** [comment]
Daisy UI isn't a component framework in the same way that Material UI is. It doesn't have any behaviours. It's mainly just a component framework built from the utility classes of Tailwind.

This is the example of a JSX modal component from their docs:

```
{/* Open the modal using document.getElementById('ID').showModal() method */}
<button className="btn" onClick={()=>document.getElementById('my_modal_1').showModal()}>open modal</button>
<dialog id="my_modal_1" className="modal">
  <div className="modal-box">
    <h3 className="font-bold text-lg">Hello!</h3>
    <p className="py-4">Press ESC key or click the button below to close</p>
    <div className="modal-action">
      <form method="dialog">
        {/* if there is a button in form, it will close the modal */}
        <button className="btn">Close</button>
      </form>
    </div>
  </div>
</dialog>
```

Note that you have to handle the behaviour yourself with JavaScript.

Daisy UI is phone compatible insofar as CSS is.

**Comment by jordyarms** [comment]
I'm operating from assumptions right now on what I think the two of you want this app to do.
Can you two as users define your simple user flows of what actions the you should be able to do so we can qualify the design decisions and requirements?

examples 1 - user adds decks
1. user gets deck list out of moxfield / edhrec / ???
2. user submits deck list into unisleevr
3. repeat

examples 2 - user identifies shared cards
1. user defines a card they want to have shared between decks
2. user adds to their card pool

This will help me understand what we're aiming for. 
As of right now the import approach of list management might not be the design direction we want to go in. 

That said, approving as is.

**Review by jordyarms — APPROVED** [review]
see comments.

**Pull request merged**
